version: '3.8'

services:
  db:
    image: postgres:14.17
    container_name: recipe_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: recipesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./cookbook-data.sql:/docker-entrypoint-initdb.d/cookbook-data.sql

  app:
    build: .
    container_name: cookbook_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/recipesdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  pgdata: